# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-18 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospede',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
