# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quartos', '0001_initial'),
        ('hospedes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospedagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateField(default=django.utils.timezone.now)),
                ('proximo_vencimento', models.DateField()),
                ('dia_vencimento', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('observacao', models.CharField(blank=True, max_length=90, null=True)),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospedes.Hospede')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quartos.Quarto')),
            ],
            options={
                'verbose_name_plural': 'Hospedagem',
            },
        ),
    ]
