# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=4)),
                ('descricao', models.CharField(blank=True, max_length=30, null=True)),
                ('banheiro', models.CharField(choices=[('COL', 'Coletivo'), ('COM', 'Compartilhado'), ('S', 'Su\xedte')], default='COL', max_length=3)),
            ],
        ),
    ]
