# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
