# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-18 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0002_auto_20190116_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quarto',
            options={'ordering': ['numero']},
        ),
    ]
